import Head from "next/head";
import Script from "next/script";
import styles from "../styles/home.module.css";
import Image from "next/image";

const Index = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog Hunt</title>
        <meta name="description" content="Generated By create-next-app" />
      </Head>
      {/* <Script src="" strategy="lazyOnLoad"></Script> */}
      
      <h1 className={styles.blogtitle}>Blog Hunt</h1>
      {/* <Image className={styles.myimg} src="/codingimage.jpg" width={237} height={158}/> */}
      <img className={styles.myimg} src="/codingimage.jpg" width={300 } height={158} alt="BlogHunt" />
      <p>A blog for hunting coders by a hunting coder</p>

      {/* Latest Blogs Section */}
      <h2 className={styles.latestBlogsTitle}>Latest Blogs</h2>
      <ul className={styles.blogList}>
        <li className={styles.blogItem}>
          <h3 className={styles.blogHeading}>Understanding React</h3>
          <p className={styles.blogDescription}>
            A deep dive into React.js, its component lifecycle, and hooks that make it an amazing JavaScript library for building user interfaces.
          </p>
        </li>
        <li className={styles.blogItem}>
          <h3 className={styles.blogHeading}>CSS Grid and Flexbox</h3>
          <p className={styles.blogDescription}>
            Learn the differences between CSS Grid and Flexbox, and how to use them to create complex, responsive layouts.
          </p>
        </li>
        <li className={styles.blogItem}>
          <h3 className={styles.blogHeading}>JavaScript ES6 Features</h3>
          <p className={styles.blogDescription}>
            Explore the new features introduced in ES6, including arrow functions, promises, and the spread/rest operator, to enhance your JavaScript skills.
          </p>
        </li>
        <li className={styles.blogItem}>
          <h3 className={styles.blogHeading}>Introduction to Node.js</h3>
          <p className={styles.blogDescription}>
            An introduction to server-side JavaScript with Node.js, understanding the basics, and building a simple server.
          </p>
        </li>
      </ul>
    </div>
  );
};

export default Index;
